apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pihole
  namespace: argocd

spec:
  generators:
  - list:
      elements:
      - name: k-demo
        server: https://k-demo.home.net

  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: '{{name}}-pihole'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/lknite/demos.git
        targetRevision: HEAD
        path: apps/pihole/base

        helm:
          releaseName: "pihole"
          parameters:
          - name: pihole.ingress.tls[0].hosts
            value: "{pihole.{{name}}.k.home.net}"
          - name: pihole.ingress.tls[0].secretName
            value: "pihole.{{name}}.k.home.net-tls"
          - name: pihole.ingress.hosts
            value: '{pihole.{{name}}.k.home.net}'

      destination:
        server: '{{server}}'
        namespace: pihole

      syncPolicy:
        syncOptions:
        - CreateNamespace=true

        automated:
          selfHeal: true
          prune: true
