pihole:

  serviceDns:
    type: LoadBalancer
    #loadBlancerIP: ""

  admin:
    # -- Specify an existing secret to use as admin password
    existingSecret: "pihole-password"
    # -- Specify the key inside the secret to use
    passwordKey: "password"

  persistentVolumeClaim:
    enabled: false

  serviceDhcp:
    enabled: false

  extraEnvVars:
    TZ: Canada/Vancouver
    DNS_BOGUS_PRIV: false
    DNS_FQDN_REQUIRED: false
    DNS_FQDN_REQUIRED: false
    DNSMASQ_USER: root
    DNSMASQ_LISTENING: all

#  ingress:
#    enabled: true
#    ingressClassName: nginx
#    annotations:
#      cert-manager.io/issuer: "cluster-adcs-issuer"                   #use specific name of issuer
#      cert-manager.io/issuer-kind: "ClusterAdcsIssuer"                #or ClusterAdcsIssuer
#      cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"

  DNS1: "10.0.0.2"
  DNS2: "10.0.0.3"

  podDnsConfig:
    enabled: false
